### ISSUE TITLE
Update ymodules version

### ISSUE THREAD

**Issue by tadatuta** [enb-make/enb-modules#10]

**Comment by gela-d** [comment]
Вов, кому жмет и насколько срочно?

**Comment by tadatuta** [comment]
Связанная задача прилинкована. Можно считать, что жмет мне. По срокам как обычно — чем быстрее, тем лучше, но все бросать, конечно, не нужно.

**Comment by blond** [comment]
У `ym` стоит мягкая зависимость. Последняя версия приедет при установке.
